DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS art;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE admin(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


CREATE TABLE cart(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  --author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL
  --price INTEGER NOT NULL
  --body TEXT NOT NULL,
  KEY (custid) REFERENCES user (id)
);

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  --author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL
  price INTEGER NOT NULL
  --body TEXT NOT NULL,
  --FOREIGN KEY (author_id) REFERENCES user (id)
);
