DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS purchased_images;
DROP TABLE IF EXISTS cart;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE admin(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE purchased_images (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    filename TEXT NOT NULL,
    purchased_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE cart(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  custid INTEGER ,
  --author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  --price INTEGER NOT NULL
  --body TEXT NOT NULL,
  FOREIGN KEY (custid) REFERENCES user (id)
);

-- CREATE TABLE image (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   --author_id INTEGER NOT NULL,
--   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   title TEXT NOT NULL,
--   price INTEGER NOT NULL
--   --body TEXT NOT NULL,
--   --FOREIGN KEY (author_id) REFERENCES user (id)
-- );
